### ISSUE TITLE
Change Type To Spline

### ISSUE THREAD

**Issue by dodekeract** [emilmork/react-rt-chart#1]
How would I do that? I tried using this code:

````jsx
<RTChart
	chart={{
		interaction: {
			enabled: false
		},
		point: {
			show: false
		},
		data: {
			type: 'spline'
		}
	}}
	maxValues={60}
	data={Object.assign({
		temperature: temperature,
		humidity: humidity,
		brightness: brightness,
		date: new Date()
	})}
	fields={fields}
/>
````

However, this doesn't work.

**Comment by emilmork** [comment]
Hi!

1. Does it work without `type: 'spline'` ? 
2. What exactly is not working ?

**Comment by dodekeract** [comment]
It doesn't change the data type, charts works the same as before inserting the data argument.

**Comment by emilmork** [comment]
Okey. And `type: 'spline'` is set initially, and not dynamic after first render ?

Have you tried some other chart types ? If its only spline thats not working there might be the c3 version, if not i guess there is a issue with the config merge.

I will take a look :)

**Comment by dodekeract** [comment]
No, it should be set initially.

**Comment by emilmork** [comment]
I looked at the sourcecode and I can see why its not working.

I will publish a new patch during the next days.

**Comment by dodekeract** [comment]
Thanks!

**Comment by emilmork** [comment]
Chart types is now working in the latest patch. https://github.com/emilmork/react-rt-chart/commit/86c26588958874bc704a32d0b4af655629ac7f03

**Comment by dodekeract** [comment]
Can confirm, works now, thanks.
