### ISSUE TITLE
Dependency 'react' and 'react-dom' creates conflicts

### ISSUE THREAD

**Issue by Brightergy-JonathanHockman** [emilmork/react-rt-chart#2]
It looks like perhaps 'react' and 'react-dom' should not be in the dependencies for the package.json. Whenever we install your module using npm install it pulls in a second 'react' and 'react-dom' installation which prevents the chart from rendering because 'react' is already installed once. After reviewing several other react modules they do not have the 'react' or 'react-dom' listed in the dependencies, I assume, because if you're using this module then you are using React already. We had to delete both folders under `react-rt-chart/node_modules` in order to fix the problem locally, but this will not fix deployment since it pulls in your module at build time.

Is there another way to accomplish this, so we can ignore those dependencies within your package.json if you're opposed to modifying your pacakage.json file?

Great module btw, I don't want to come across as sounding too critical.

Thanks!

**Comment by dodekeract** [comment]
A temporary workaround would be to include a rm -r as a postinstall script. This should automatically apply your workaround.

**Comment by Brightergy-SamarAcharya** [comment]
Moving `react` and `react-dom` to `devDependencies` fixed the issue for us. Also, I think its better to do it this way as they are only development dependencies for this module and should not be strict dependency for other packages/apps using this module. thoughts?

**Comment by emilmork** [comment]
Yes @Brightergy-JonathanHockman. It should be a devDependency. I will look at your PR tonight and possibly add a new patch :+1:

**Comment by Brightergy-EmmanuelEkochu** [comment]
@emilmork Thanks for addressing this issue.

**Comment by emilmork** [comment]
Fixed by [#3](https://github.com/emilmork/react-rt-chart/pull/3)

**Comment by emilmork** [comment]
@Brightergy-EmmanuelEkochu I have published a new patch including [#3](https://github.com/emilmork/react-rt-chart/pull/3). Thanks!

**Comment by Brightergy-EmmanuelEkochu** [comment]
Thanks Emil we shall test it out later.

--
Emmanuel*Ekochu*
Brightergy | Technology Development Manager
1712 Main Street, 6th Floor, Kansas City, MO 64108
office: +1.816.897.1010
fax: +1.888.511.0822

*www.brightergy.com <http://www.brightergy.com>*
Boston | Kansas City | St. Louis

**Comment by alexsmartens** [comment]
I had  the same problem. The problem's solved with installing `react-dom`. Can you add it to the dependencies list?

**Comment by emilmork** [comment]
@alexsmartens I can take a look at react-dom as a dependency.
