### ISSUE TITLE
chart axis x type could not set others

### ISSUE THREAD

**Issue by duckscofield** [emilmork/react-rt-chart#5]
src/index.js line 135    **chart_temp.axis.x.type = 'timeseries';**

When I use another chart type, I want to change this value to 'indexed' (c3.js API default), but this line will always overwrite my setting, the chart axis will all the time, not my defined data (ex: http://c3js.org/samples/chart_scatter.html)

another issue: data.x = 'x' is default for Date object in source code, it lock the x value

**Comment by duckscofield** [comment]
Could this lib support all types with C3.js?

line
spline
step
area
area-spline
area-step
bar
scatter
pie
donut
gauge

Thank you :)

**Comment by duckscofield** [comment]
Sorry, I click 'closed' button by mistake

**Comment by emilmork** [comment]
The lib was intended to only be used for `real-time` data only, but you can try make it work with other chart types. I would love to see a pull request :)

I am not sure how it will behave but you can try this:

```
    var chart_temp = merge({
      axis: {
        x: {
          type: 'timeseries',
          tick: {
            format: '%H:%M:%S',
          }
        }
      },
      data: {
        x: 'x', // I think its ok that this is default since its a `real-time` chart
        columns: columns
      }
    }, (chart || {}));
    
    // chart_temp.axis.x.type = 'timeseries'; // REMOVE THIS LINE

**Comment by duckscofield** [comment]
Dear emilmork, I have made a PR

**Comment by emilmork** [comment]
Great @duckscofield. I will deploy a new version tonight after work.

**Comment by emilmork** [comment]
@duckscofield New version is out.
