### ISSUE TITLE
unable to double click on chart

### ISSUE THREAD

**Issue by mavisjheng** [emilmork/react-rt-chart#7]
I am trying to add double click event to chart so can have interaction with it, such as: change its style or edit data source. However every time I double click it, it always triggers the parent click event. From source code, the div only accepts the style props, is it okay if div accepts onDoubleClick props ? Thanks.

` return <div style = { this.props.style } ref='chart'/>`
`return <div style = { this.props.style } onDoubleClick = { this.props.onDoubleClick } ref='chart'/>`

**Comment by emilmork** [comment]
Hi! @mavisjheng.

 I can look at it, but I am a bit busy right now. If you make a PR I will happily merge it :D

Take a look at [Transferring-props-react](http://reactjs.cn/react/docs/transferring-props.html). It might be a good idea to transfer all props.

**Comment by mavisjheng** [comment]
Hi @emilmork 

I made a PR, thanks : )

**Comment by emilmork** [comment]
@mavisjheng Greate! I will look into it tonight and merge/deploy a new version.

**Comment by emilmork** [comment]
Resolved by [#8](https://github.com/emilmork/react-rt-chart/pull/8)
